export * from './createPluralize'
export * from './setToLocalStorage'
export { checkPhoto } from './checkPhoto'
export { convertFileToBase64 } from './convertFileToBase64'
export { getCroppedImg } from './getCroppedImg'
export { getInitials } from './getInitials'
export { handleErrorResponse } from './handleErrorResponse'
