export * from './Boy.png'
export * from './FlagRussia.svg'
export * from './FlagUK.svg'
export * from './Girl.png'
export * from './avatar.png'
export * from './datePicker.png'
export * from './noAva.webp'